<script setup lang="ts">

// import MyComponent from '@/components/MyComponent.vue';
</script>

<template>
  <div class="policy-container">
    <v-container>
      <v-row justify="center">
        <v-col cols="12" md="10" lg="8">
          <h1 class="text-h3 mb-6 text-center">Privacy Policy</h1>
          <p class="text-subtitle-1 mb-6 text-center text-medium-emphasis">Last updated: April 22, 2026</p>

          <v-card class="mb-6 pa-4" variant="outlined">
            <div class="text-body-1">
              <h2 class="text-h5 mb-4">1. Introduction</h2>
              <p class="mb-4">
                At Screenshot Magician, we take your privacy seriously. This Privacy Policy explains how we collect, use, 
                and protect your information when you use our service. Screenshot Magician is open-source software 
                released under the MIT License, and our commitment to privacy is reflected in our source code which 
                is publicly available for review.
              </p>

              <h2 class="text-h5 mb-4">2. Information We Don't Collect</h2>
              <p class="mb-4">
                Screenshot Magician is designed with privacy in mind. We do not collect or store:
              </p>
              <ul class="mb-4">
                <li>Store your images or chat logs</li>
                <li>The text content of your imported chat logs</li>
                <li>Direct personal identifiers such as your real name, email address, or account credentials through the app itself</li>
                <li>Uploaded copies of your projects or exported screenshots on our stats backend</li>
              </ul>
              <p class="mb-4">
                Please see the sections below for details on limited browser storage, service telemetry, and third-party analytics.
              </p>

              <h2 class="text-h5 mb-4">3. Local Storage</h2>
              <p class="mb-4">
                We use browser storage, including local storage, session storage, cookies, and IndexedDB, to:
              </p>
              <ul class="mb-4">
                <li>Save your character name preference</li>
                <li>Remember your last editor state</li>
                <li>Store your canvas dimensions</li>
                <li>Persist saved projects and editor sessions locally in your browser</li>
                <li>Remember tutorial, settings, theme, and interface preferences</li>
                <li>Store pseudonymous visitor and session identifiers used for the live usage tracker</li>
              </ul>
              <p class="mb-4">
                Most of this data stays only in your browser. Visitor and session identifiers used for the live usage tracker are also sent to our backend so we can count visits, active sessions, and export activity without storing your image or chat content.
              </p>

              <h2 class="text-h5 mb-4">4. Image Processing</h2>
              <p class="mb-4">
                All image processing occurs locally in your browser. Your images and chat logs are never uploaded 
                to any server and remain entirely on your device.
              </p>

              <h2 class="text-h5 mb-4">5. Service Telemetry and Live Usage Tracker</h2>
              <p class="mb-4">
                We operate a lightweight backend service that records limited pseudonymous usage information to power the live community tracker and understand product usage. This telemetry may include:
              </p>
              <ul class="mb-4">
                <li>Pseudonymous visitor and session identifiers generated by your browser</li>
                <li>Session starts and recent activity timestamps used to estimate active users</li>
                <li>Page path information, such as whether activity occurred on the home page or editor route</li>
                <li>Counts of successful image exports</li>
                <li>Aggregate totals such as unique visitors, visits, exporters, and exports</li>
              </ul>
              <p class="mb-4">
                This telemetry is used for operational insight and public-facing aggregate counters. It is not used to upload or inspect your image files, chat logs, or exported screenshots.
              </p>

              <h2 class="text-h5 mb-4">6. Analytics</h2>
              <p class="mb-4">
                To understand how our service is used and to improve user experience, we utilize Google Analytics. Google Analytics collects information such as:
              </p>
              <ul class="mb-4">
                <li>How often users visit the site</li>
                <li>What pages users visit when they do so</li>
                <li>What other sites they used prior to coming to our site</li>
                <li>Approximate geographical location</li>
                <li>Browser and device information</li>
              </ul>
              <p class="mb-4">
                Google Analytics collects only the IP address assigned to you on the date you visit this site, rather than your name or other identifying information. We do not combine the information collected through the use of Google Analytics with personally identifiable information. Although Google Analytics plants a permanent cookie on your web browser to identify you as a unique user the next time you visit this site, the cookie cannot be used by anyone but Google. Google’s ability to use and share information collected by Google Analytics about your visits to this site is restricted by the <a href="https://marketingplatform.google.com/about/analytics/terms/us/" target="_blank" rel="noopener">Google Analytics Terms of Use</a> and the <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google Privacy Policy</a>. You can prevent Google Analytics from recognizing you on return visits to this site by disabling cookies on your browser or by installing the <a href="https://tools.google.com/dlpage/gaoptout/" target="_blank" rel="noopener">Google Analytics Opt-out Browser Add-on</a>.
              </p>

              <h2 class="text-h5 mb-4">7. Third-Party Services</h2>
              <p class="mb-4">
                Other than Google Analytics as described above, our website may contain links to third-party websites or services. We are not responsible for 
                the privacy practices or content of these external sites.
              </p>

              <h2 class="text-h5 mb-4">8. Children's Privacy</h2>
              <p class="mb-4">
                Our service is not directed to children under 13. We do not knowingly collect or store any 
                personal information from children under 13.
              </p>

              <h2 class="text-h5 mb-4">9. Changes to This Policy</h2>
              <p class="mb-4">
                We may update this Privacy Policy from time to time. We will notify you of any changes by 
                posting the new Privacy Policy on this page and updating the "Last updated" date.
              </p>

              <h2 class="text-h5 mb-4">10. Contact Us</h2>
              <p class="mb-4">
                If you have any questions about this Privacy Policy, please contact us:
              </p>
              <ul>
                <li>Via GitHub: <a href="https://github.com/SomniForge" target="_blank" rel="noopener">@SomniForge</a></li>
                <li>Via Twitter: <a href="https://twitter.com/SomniForge" target="_blank" rel="noopener">@SomniForge</a></li>
              </ul>
            </div>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style scoped>
.policy-container {
  padding: 32px 16px;
  min-height: 100%;
  background-color: #121313;
  overflow-y: auto;
  height: 100%;
  position: relative;
}

.v-container {
  max-width: 1200px;
  margin: 0 auto;
}

h1, h2 {
  color: #ffffff;
}

a {
  color: #42a5f5;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

ul {
  padding-left: 24px;
  margin-bottom: 16px;
}

li {
  margin-bottom: 8px;
}

.v-card {
  background-color: #1E1E1E !important;
  color: #E0E0E0 !important;
}
</style>
